# Julia vs. R. 矩陣乘法

- Author. jw.
- Date. May 27, 2024.

## Problem. 今天簡單比較 julia 跟 r 的矩陣功能。

In [2]:
using LinearAlgebra
using RCall
using Random, Distributions

In [13]:
A = randn(3,3)
B = diagm(ones(3))

@rput A B

A

3×3 Matrix{Float64}:
 0.311636   -0.789185    1.24488
 0.0594999  -0.612494   -0.535426
 0.888831   -0.0633075   1.09319

In [17]:
## 元素對應相乘 elementwise multiplication
A .* B

3×3 Matrix{Float64}:
 0.311636  -0.0        0.0
 0.0       -0.612494  -0.0
 0.0       -0.0        1.09319

In [15]:
R"A * B"

RObject{RealSxp}
          [,1]      [,2]    [,3]
[1,] 0.3116357  0.000000 0.00000
[2,] 0.0000000 -0.612494 0.00000
[3,] 0.0000000  0.000000 1.09319


In [18]:
## 矩陣相乘 matrix multiplication
A * B

3×3 Matrix{Float64}:
 0.311636   -0.789185    1.24488
 0.0594999  -0.612494   -0.535426
 0.888831   -0.0633075   1.09319

In [19]:
R"A %*% B"

RObject{RealSxp}
           [,1]        [,2]       [,3]
[1,] 0.31163573 -0.78918476  1.2448791
[2,] 0.05949988 -0.61249398 -0.5354256
[3,] 0.88883134 -0.06330749  1.0931901


In [23]:
## 內積 \cdot
dot(A, B)
# OR A ⋅ B

0.7923318975059308

In [24]:
R"sum(A*B)"

RObject{RealSxp}
[1] 0.7923319
