# Julia vs. R. 矩陣乘法

- Author. jw.
- Date. May 27, 2024.

## Problem. 

今天簡單比較 julia 跟 r 的矩陣功能。

## Solution.

In [1]:
using LinearAlgebra
using RCall
using Random, Distributions

In [2]:
A = randn(3,3)
B = diagm(ones(3))

@rput A B

A

3×3 Matrix{Float64}:
 -1.14544   -0.70488    -0.924749
  0.242865   1.65682     0.113084
 -0.478499   0.0676163   0.470498

1. 元素對應相乘 elementwise multiplication, Hadamard product 

In [3]:
## Hadamard product 
A .* B

3×3 Matrix{Float64}:
 -1.14544  -0.0      -0.0
  0.0       1.65682   0.0
 -0.0       0.0       0.470498

In [4]:
R"A * B"

RObject{RealSxp}
          [,1]    [,2]      [,3]
[1,] -1.145436 0.00000 0.0000000
[2,]  0.000000 1.65682 0.0000000
[3,]  0.000000 0.00000 0.4704984


2. 矩陣相乘

In [5]:
## matrix multiplication
A * B

3×3 Matrix{Float64}:
 -1.14544   -0.70488    -0.924749
  0.242865   1.65682     0.113084
 -0.478499   0.0676163   0.470498

In [6]:
R"A %*% B"

RObject{RealSxp}
           [,1]        [,2]       [,3]
[1,] -1.1454361 -0.70487967 -0.9247492
[2,]  0.2428647  1.65682034  0.1130844
[3,] -0.4784994  0.06761633  0.4704984


3. 內積。 Inner product.

$A \cdot B = |A| |B| \cos(\theta) = \sum _I a_i b_i$

In [7]:
## 內積 \cdot
dot(A, B)
# OR A ⋅ B

0.9818825503021242

In [8]:
R"sum(A*B)"

RObject{RealSxp}
[1] 0.9818826


4. 轉置 transpose

In [9]:
A'

3×3 adjoint(::Matrix{Float64}) with eltype Float64:
 -1.14544   0.242865  -0.478499
 -0.70488   1.65682    0.0676163
 -0.924749  0.113084   0.470498

In [10]:
R"t(A)"

RObject{RealSxp}
           [,1]      [,2]        [,3]
[1,] -1.1454361 0.2428647 -0.47849936
[2,] -0.7048797 1.6568203  0.06761633
[3,] -0.9247492 0.1130844  0.47049836


## Discussion.

簡單來說， julia 預設的乘法 （`*`） 是「矩陣乘法」。
用 `.*` 可廣播運算，相當於「元素對應乘法」。
補充說明，這邊 julia 的設計跟 matlab 是比較接近的。

而 r 預設的乘法 `*` 則是「元素乘法」。
透過特殊的運算子 `%*%` 來計算「矩陣乘法」。
補充說明，這邊 r 跟 python 倒是蠻像的，
python 的預設乘法 `*` 也是元素乘法， 用特殊運算子 `@` 做矩陣乘法。

